secrets:
  database:
    file: ../secrets/database.txt
  other_user:
    file: ../secrets/other_user.txt
  admin:
    file: ../secrets/admin.txt


networks:
  my_network:
    driver: bridge

volumes:
  wordpress_volume:
    driver: local
    driver_opts:
      type: none
      device: ${HOME}/data/wordpress
      o: bind
  mariadb_volume:
    driver: local
    driver_opts:
      type: none
      device: ${HOME}/data/mariadb
      o: bind

services:
  nginx:
    build: requirements/nginx
    image: nginx:4.2
    container_name: nginx
    ports:
      - "443:443"
    restart: always
    volumes:
      - wordpress_volume:/var/www/html
    depends_on:
      - wordpress
      - mariadb
    networks:
      - my_network
    expose:
      - "443"

  wordpress:
    build: requirements/wordpress
    image: wordpress:4.2
    container_name: wordpress
    restart: always
    volumes:
      - wordpress_volume:/var/www/html
    expose:
      - "9000"
    networks:
      - my_network
    env_file:
      - .env
    depends_on:
      - mariadb
    secrets:
      - database
      - admin
      - other_user

  mariadb:
    build: requirements/mariadb
    image: mariadb:4.2
    container_name: mariadb
    restart: always
    secrets:
      - database
    volumes:
      - mariadb_volume:/var/lib/mysql
    expose:
      - "3306"
    networks:
      - my_network

