secrets:
  db_password:
    file: ../secrets/db_password.txt
  db_root_password:
    file: ../secrets/db_root_password.txt
  credentials:
    file: ../secrets/credentials.txt

networks:
  my_network:
    driver: bridge

volumes:
  wordpress_volume:
    driver: local
    driver_opts:
      type: none
      device: /home/bdemirbu/Desktop/deneme
      o: bind
services:
  nginx:
    build: requirements/nginx
    container_name: nginx
    ports:
      - "443:443"
    restart: always
    volumes:
      - wordpress_volume:/var/www/html
    depends_on:
      - wordpress
    networks:
      - my_network
    env_file:
      - .env
    secrets:
      - db_password
      - db_root_password
      - credentials
  wordpress:
    build: requirements/wordpress
    container_name: wordpress
    restart: always
    volumes:
      - wordpress_volume:/var/www/html
    expose:
      - "9000"
    networks:
      - my_network
    env_file:
      - .env
  mariadb:
    build: requirements/mariadb
    container_name: mariadb
