secrets:
  database:
    file: ../secrets/database.txt
  sqluser:
    file: ../secrets/sqluser.txt
  admin:
    file: ../secrets/admin.txt


networks:
  my_network:
    driver: bridge

volumes:
  wordpress_volume:
    driver: local
    driver_opts:
      type: none
      device: ${HOME}/Desktop/wordpress
      o: bind
  mariadb_volume:
    driver: local
    driver_opts:
      type: none
      device: ${HOME}/Desktop/mariadb
      o: bind

services:
  nginx:
    build: requirements/nginx
    container_name: nginx
    ports:
      - "443:443"
    restart: always
    volumes:
      - wordpress_volume:/var/www/html
    depends_on:
      - wordpress
      - mariadb
    networks:
      - my_network
    expose:
      - "443"
    env_file:
      - .env
    secrets:
      - database
  wordpress:
    build: requirements/wordpress
    container_name: wordpress
    restart: always
    volumes:
      - wordpress_volume:/var/www/html
    expose:
      - "9000"
    networks:
      - my_network
    env_file:
      - .env
    depends_on:
      - mariadb
    secrets:
      - database
      - sqluser
      - admin
  mariadb:
    build: requirements/mariadb
    container_name: mariadb
    restart: always
    secrets:
      - database
    env_file:
      - .env
    volumes:
      - mariadb_volume:/var/lib/mysql
    expose:
      - "3306"
    networks:
      - my_network

